# Generated by Django 4.1.6 on 2023-03-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malc', '0003_delete_destination_remove_reviews_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
