# Generated by Django 4.1.6 on 2023-03-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malc', '0004_reviews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
